name: alfcapp
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  cloud_firestore:
  firebase_database:
  intl:
  progress_hud:
  utils:
  firebase_core:
  url_launcher:
  flutter_staggered_grid_view:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/pic-01.png
    - assets/pic-02.png
    - assets/pic-03.png
    - assets/logo.png
    - assets/otherlogo.png
    - assets/splashcreen.png
    - assets/ultimate.jpg
    - assets/ACHEIVER.jpg
    - assets/aloft.jpg
    - assets/ayyan_logo.png
    - assets/bag.png
    - assets/malik.jpg
    - assets/modern.png
    - assets/ms.jpg
    - assets/deluxe.png
    - assets/anon.png
    - assets/logo_blah.png





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Open Sans Condensed
      fonts:
        - asset: assets/fonts/OpenSansCondensed-Light.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        #- asset: assets/fonts/OpenSans-Bold.ttf
         # style: bold
    - family: OpenSansCondensed
      fonts:
        - asset: assets/fonts/OpenSansCondensed-Bold.ttf
       #   style: bold
      #  - asset: assets/fonts/OpenSansCondensed-Light.ttf
       #   style: light
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf



  #       - asset: fonts/Schyler-Italic.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
